# Generated by Django 5.1.6 on 2025-03-05 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carros',
            name='foto',
            field=models.ImageField(default=1, upload_to='media/carros'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carousel',
            name='imagens',
            field=models.ImageField(upload_to='media/carousel'),
        ),
    ]
