# Generated by Django 5.1.6 on 2025-03-05 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0002_carros_foto_alter_carousel_imagens'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carros',
            name='descrição',
        ),
    ]
