# Generated by Django 5.1.6 on 2025-03-05 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0003_remove_carros_descrição'),
    ]

    operations = [
        migrations.AddField(
            model_name='carros',
            name='descrição',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
