# Generated by Django 5.1.6 on 2025-03-05 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0004_carros_descrição'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='nome',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
