# Generated by Django 5.1.6 on 2025-03-05 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0005_carousel_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carousel',
            old_name='imagens',
            new_name='foto',
        ),
    ]
