# Generated by Django 5.1.6 on 2025-03-05 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0008_alter_carousel_foto_alter_carros_foto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carros',
            name='valor',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
