# Generated by Django 5.1.6 on 2025-03-05 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0010_carousel_descrcao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carros',
            name='valor',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
    ]
